<!DOCTYPE html>
<html>
<head>
    <style>
        body { background-color: #030407; color: #ffffff; font-family: monospace; padding: 20px; }
        .container { border: 1px solid #00ffe7; padding: 30px; max-width: 600px; margin: 0 auto; background-color: #0a0c12; text-align: center; }
        h1 { color: #00ffe7; border-bottom: 1px dashed #00ffe7; padding-bottom: 10px; text-transform: uppercase; }
        .otp-box { background-color: rgba(0, 255, 231, 0.1); border: 2px dashed #00ffe7; padding: 20px; font-size: 2.5rem; letter-spacing: 5px; color: #00ffe7; font-weight: bold; margin: 30px 0; border-radius: 8px; }
        .footer { margin-top: 30px; font-size: 0.8rem; color: #555; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Decryption Key Requested</h1>
        <p>A request was made to override the security protocols on your HyperLife OS account.</p>
        <p>Enter the following 6-digit key into the console to verify your identity. This key will self-destruct in <strong>10 minutes</strong>.</p>
        
        <div class="otp-box">
            {{ $otp }}
        </div>

        <p style="color: #ef4444; font-size: 0.85rem;">If you did not initiate this sequence, ignore this transmission. Your matrix is secure.</p>

        <div class="footer">
            Generated by the HyperLife Sentient Core.
        </div>
    </div>
</body>
</html>