<!DOCTYPE html>
<html>
<head>
    <style>
        body { background-color: #030407; color: #ffffff; font-family: monospace; padding: 20px; }
        .container { border: 1px solid #00ffe7; padding: 30px; max-width: 600px; margin: 0 auto; background-color: #0a0c12; }
        h1 { color: #00ffe7; border-bottom: 1px dashed #00ffe7; padding-bottom: 10px; text-transform: uppercase; }
        .alert { background-color: rgba(239, 68, 68, 0.2); border-left: 4px solid #ef4444; padding: 15px; color: #fca5a5; margin-bottom: 20px; }
        .stats { margin-bottom: 20px; background: rgba(255,255,255,0.05); padding: 15px; border-radius: 6px; border: 1px solid #333; }
        .stats span { color: #a855f7; font-weight: bold; font-size: 1.2rem; }
        .footer { margin-top: 40px; font-size: 0.8rem; color: #555; text-align: center; border-top: 1px dashed #333; padding-top: 15px; }
        .btn { display: inline-block; background-color: #00ffe7; color: #000; padding: 12px 25px; text-decoration: none; font-weight: bold; margin-top: 20px; text-transform: uppercase; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Uplink Established</h1>
        <p>Good morning, Operator <strong style="color: #fff;">{{ $user->name }}</strong>.</p>
        
        <div class="stats">
            <p>Current Clearance: <span>LEVEL {{ $user->level }}</span></p>
            <p>Available Mass: <span>{{ $user->xp }} XP</span></p>
        </div>

        @if($deadPlanetsCount > 0)
        <div class="alert">
            <strong>⚠️ CRITICAL ENTROPY DETECTED</strong><br><br>
            {{ $deadPlanetsCount }} of your orbital nodes have decayed due to inactivity. Log in immediately to execute defense protocols and restore mass.
        </div>
        @else
        <p style="color: #10b981; padding: 10px; border-left: 3px solid #10b981; background: rgba(16,185,129,0.1);">
            ✓ All orbital nodes are stable. Maintain current velocity.
        </p>
        @endif

        @if($activeDuels > 0)
        <p style="color: #ffb86c; padding: 10px; border-left: 3px solid #ffb86c; background: rgba(255,184,108,0.1);">
            ⚔️ You have <strong>{{ $activeDuels }}</strong> active combat wagers in the Colosseum. Do not let your opponent strike first.
        </p>
        @endif

        <div style="text-align: center;">
            <a href="http://localhost:5173/dashboard" class="btn">Access Console</a>
        </div>

        <div class="footer">
            Generated by the HyperLife Sentient Core.<br>
            Transmission End.
        </div>
    </div>
</body>
</html>