<!DOCTYPE html>
<html>
<head>
    <style>
        body { background-color: #030407; color: #ffffff; font-family: monospace; padding: 20px; }
        .container { border: 1px solid #00ffe7; padding: 30px; max-width: 600px; margin: 0 auto; background-color: #0a0c12; text-align: center; }
        h1 { color: #00ffe7; border-bottom: 1px dashed #00ffe7; padding-bottom: 10px; text-transform: uppercase; }
        .otp-box { background-color: rgba(0, 255, 231, 0.1); border: 2px dashed #00ffe7; padding: 20px; font-size: 2.5rem; letter-spacing: 5px; color: #00ffe7; font-weight: bold; margin: 30px 0; border-radius: 8px; }
        .footer { margin-top: 30px; font-size: 0.8rem; color: #555; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Identity Verification Required</h1>
        <p>A request was made to initialize a new Operator profile on HyperLife OS.</p>
        <p>Enter the following 6-digit Decryption Key into the terminal to verify your comms address.</p>
        <div class="otp-box">{{ $otp }}</div>
        <p style="color: #ef4444; font-size: 0.85rem;">If you did not initiate this sequence, ignore this transmission.</p>
        <div class="footer">Generated by the HyperLife Sentient Core.</div>
    </div>
</body>
</html>